# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Velvet Vegan
email: chikfender@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  A Vegan Recipe Cooking Blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://velvetvegan.com/dev.html" # the base hostname & protocol for your site
twitter_username: velvetvegan
github_username:  velvetvegan

# Build settings
markdown: kramdown
